; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "ElsEvo"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "AyameJJ"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "ElsEvo.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

; Pasta real onde o "dotnet publish" grava a build (self-contained, single-file), pra não
; repetir o caminho inteiro em cada linha do [Files] abaixo. Se um dia mudar o
; TargetFramework do .csproj (ex.: net8.0-windows -> net9.0-windows), ajuste aqui também.
#define PublishDir "C:\Users\Victorr\OneDrive\ProjetoElsEvo\ElsEvo\bin\Release\net8.0-windows\win-x64"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
; ATENÇÃO: esse AppId precisa ser IDÊNTICO no .iss do canal beta (ElsEvoBeta) -- é o que
; permite instalar um canal por cima do outro (substituindo no lugar), em vez de instalar
; como programa duplicado. Não gere um GUID novo pro beta, copie este aqui.
AppId={{8910440C-BF7A-494D-B5AD-7F0A4DA85D60}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\Victorr\Downloads\Output

; IMPORTANTE: esse nome precisa bater exatamente com o que o atualizar-versao.yml monta
; na URL do version.json (https://.../releases/download/{tag}/ElsEvo-Setup.exe). Se mudar
; aqui, tem que mudar no workflow também (ou vice-versa). Nomes de arquivo anexados a uma
; Release são case-sensitive de verdade -- diferente do nome do repositório na URL, que o
; GitHub redireciona ignorando maiúscula/minúscula.
OutputBaseFilename=ElsEvo-Setup

; O ícone fica dentro de Assets\, não solto na raiz do projeto (o duplicado solto foi
; removido do repositório -- ver commit "Remove ícone da aplicação solto").
SetupIconFile=C:\Users\Victorr\OneDrive\ProjetoElsEvo\ElsEvo\Assets\icone_app.ico
SolidCompression=yes
WizardStyle=modern dynamic

; ===== Metadados do arquivo .exe do instalador (aba "Detalhes" nas Propriedades do
; Windows) — sem essas diretivas, o Inno Setup deixa a "Versão do arquivo" zerada
; (0.0.0.0), o idioma como "Neutro" e os campos de Empresa/Direitos autorais vazios. =====
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright=Copyright (C) 2026 {#MyAppPublisher}
VersionInfoDescription=ElsEvo Setup
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}

; ===== Fechamento automático do ElsEvo durante a atualização =====
; AppMutex faz o Inno Setup checar (via Restart Manager do Windows) se um processo com
; esse nome de mutex está rodando antes de sobrescrever os arquivos, e oferece fechar
; sozinho. O ElsEvo não cria esse mutex explicitamente hoje (o app se fecha por conta
; própria antes de chamar o instalador — ver MainWindow.BaixarEInstalarAtualizacaoAsync),
; mas deixamos isso como reforço/rede de segurança pra quando alguém rodar o instalador
; manualmente com o app ainda aberto (ex.: baixou direto da página de Releases).
AppMutex=ElsEvo_MutexPrincipal
CloseApplications=yes
RestartApplications=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Aponta direto pra pasta que o "dotnet publish" gera de verdade
; (bin\Release\net8.0-windows\win-x64\), não pra uma pasta "publish\" separada que não
; existe nesse fluxo. Com PublishSingleFile=true, tudo (exe + dependências embutidas)
; fica nessa mesma pasta.
Source: "{#PublishDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; postinstall + skipifsilent: depois que a instalação termina, oferece reabrir o ElsEvo
; automaticamente (checkbox marcado por padrão na última tela do assistente).
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent
